export type Language = "fr" | "en";

export const STRINGS = {
  en: {
    metaTitle: "Download all your Snapchat Memories with their dates | SnapMemories",
    metaDescription:
      "Save every Snapchat Memory to your computer with its real date, place and stickers. Free, nothing to install, nothing uploaded to a server.",
    ogAlt: "SnapMemories: your Snapchat Memories, sorted by date on your computer",
    videoDescription:
      "How to export your Snapchat Memories and save them with their dates, places and stickers, on the real Snapchat page.",
    skipLink: "Skip to the tool",
    navTutorial: "Tutorial",
    navFaq: "FAQ",
    otherLanguage: "Français",
    eyebrow: "Free · Nothing to install · Nothing uploaded",
    heroTitle: "Get all your Snapchat Memories back, with their real dates.",
    heroLead:
      "Without a subscription, Snapchat now only lets you reach your last year of Memories and your oldest 5 GB. To keep the rest, you have to export it. Problem is, the export comes out messy: no date inside the photos, no place, stickers on the side. SnapMemories puts all of that back in order, right in your browser.",
    heroCta: "Get my Memories back",
    heroTutorial: "Watch the video tutorial",
    heroPoint1: "Photos in original quality",
    heroPoint2: "Works even if Snapchat sends several ZIP files",
    heroPoint3: "Open source",
    problemTitle: "What's wrong with the Snapchat export",
    problemLead:
      "Snapchat does give your files back, just not in a shape your photo app gets. Here's what a real export looks like, and what SnapMemories fixes.",
    columnTopic: "What",
    columnRaw: "Raw Snapchat export",
    columnFixed: "With SnapMemories",
    rowDate: "Date",
    rowDateRaw:
      "The date isn't inside the photo. It only lives in the file name and file date, and it's gone as soon as you copy or send it.",
    rowDateFixed: "The exact date and time are written inside every photo and video, in your own time zone.",
    rowPlace: "Place",
    rowPlaceRaw: "GPS positions sit in a separate technical file nobody ever opens.",
    rowPlaceFixed: "The place is written in the file, so Google Photos and Apple Photos put it on the map.",
    rowStickers: "Stickers",
    rowStickersRaw: "Text, stickers and drawings come as a transparent file on the side.",
    rowStickersFixed: "They're stuck back on the photo, just like when you posted it.",
    rowSorting: "Sorting",
    rowSortingRaw: "Hundreds of files with unreadable names, all in the same folder.",
    rowSortingFixed: "One folder per month, and every file is named after its date.",
    tutorialTitle: "The video tutorial, on the real Snapchat page",
    tutorialLead: "51 seconds, with sound. Click a step to jump straight to it.",
    toolTitle: "Get your Memories back",
    toolLead:
      "Got your ZIP files? Drop them right below. Not yet? The tutorial above shows you how to get them.",
    dropTitle: "Drop your Snapchat ZIP files here",
    dropHint: "or click to pick them. If there are several, drop them all at once.",
    dropPrivacy: "Nothing is uploaded: your files are read in this tab, that's it.",
    reading: "Reading your export",
    photos: "Photos",
    videos: "Videos",
    size: "Size",
    noteLocated: "With a location: {count}",
    noteMissing:
      "Not found in these files: {count}. If Snapchat sent you several ZIP files, drop them all together.",
    noteLinkOnly: "Only available as links: {count}. Request a new export on Snapchat to get them as files.",
    chooseFolder: "Choose where to save",
    chooseFolderHint:
      "Pick or create a folder, like “Snapchat Memories” in your Pictures. Anything already in there is skipped, so no duplicates.",
    downloadZip: "Save as ZIP files",
    downloadZipHint:
      "This browser can't write into a folder, so you'll get ZIP files of 1 GB max. With Chrome or Edge on a computer, it goes straight into a folder.",
    startOver: "Start over",
    savingTitle: "Saving your Memories",
    savingText: "Leave this tab open until the end.",
    saved: "Saved",
    failed: "Failed",
    remaining: "Remaining",
    stop: "Stop",
    stopping: "Stopping",
    doneTitle: "Done, everything's there!",
    doneText: "Everything is sorted by year and month.",
    doneIncompleteTitle: "Almost everything made it",
    stoppedTitle: "Import stopped",
    stoppedText: "Drop the same files again later: whatever is already saved gets skipped.",
    alreadyThere: "Already there",
    partsTitle: "Your ZIP files",
    partsText: "Downloads start by themselves. If they don't, click each file.",
    errorsTitle: "Not saved",
    importAnother: "Import another export",
    progressLabel: "{done} / {total} memories",
    skippedLabel: "Already saved, skipped: {count}.",
    leaveWarning: "Your Memories are still being saved.",
    errorInvalidZip: "{name} isn't a Snapchat ZIP file.",
    errorNoMemories: "No Memories found. Check that “Export your Memories” was turned on.",
    errorInvalidHistory: "The Memories list in this export is damaged.",
    errorNothingToImport: "There's no photo or video in these files.",
    errorFolder: "This folder doesn't work. Pick another one.",
    errorUnexpected: "Something broke. Reload the page and try again.",
    trustTitle: "Your photos never leave your device",
    trustServerTitle: "No server",
    trustServerText:
      "The page reads your ZIP files in your browser and writes the result to your disk. Nothing goes anywhere.",
    trustQualityTitle: "Original quality",
    trustQualityText:
      "A photo without stickers stays untouched, only the date and place get added inside. Photos with stickers are saved again in high quality to stick them on.",
    trustOpenTitle: "Open source",
    trustOpenText: "All the code is public on GitHub, anyone can go and check what it does.",
    faqTitle: "Questions people ask me",
    faqCostQ: "How much does it cost?",
    faqCostA: "Nothing. No account, no ads, no subscription.",
    faqSafeQ: "Is it safe?",
    faqSafeA:
      "Your export never leaves your device. There's no server behind this page: it reads the ZIP files in your browser and writes the result to your disk.",
    faqTimeQ: "How long does it take?",
    faqTimeA:
      "On the Snapchat side, the export takes a few minutes to a few hours to be ready. After that, it mostly depends on how big your export is and how fast your disk is.",
    faqPartsQ: "Snapchat sent me several ZIP files, what do I do?",
    faqPartsA: "That's normal when you have lots of Memories. Drop them all at the same time.",
    faqPhoneQ: "Can I do it on my phone?",
    faqPhoneA: "For a small export, yes. For a big library, use a computer with Chrome or Edge.",
    faqGalleryQ: "How do I put them in Google Photos or iCloud?",
    faqGalleryA: "Just upload the folder you got. The date and place are picked up on their own.",
    faqResumeQ: "What if it stops halfway?",
    faqResumeA: "Run it again with the same folder: whatever is already saved gets skipped.",
    footerSource: "Open source on GitHub",
    footerMadeBy: "Made by qyrn",
    footerDisclaimer: "SnapMemories is not affiliated with Snap Inc.",
    step1: "Open “My Data”",
    step1Caption: "Sign in on accounts.snapchat.com, then open “My Data”.",
    step2: "Turn on “Export your Memories”",
    step2Caption: "In “Select data to include”, it's the first switch.",
    step3: "Click “Request Only Memories”",
    step3Caption: "That's it on the Snapchat side. Heads up, you only get one request every 72 hours.",
    step4: "Wait for the email",
    step4Caption:
      "Snapchat emails you when it's ready, after a few minutes or a few hours. The export also shows up in “Your exports”, on the same page.",
    step5: "“See exports”, then “Download”",
    step5Caption:
      "Download every ZIP file without opening it. Don't wait too long, exports expire after 3 days.",
    step6: "Drop the ZIP files here",
    step6Caption: "Drop every ZIP file at once into the box. Nothing is uploaded.",
    step7: "Choose where to save",
    step7Caption: "Pick a folder, like in your Pictures. It starts right away.",
    step8: "All sorted",
    step8Caption: "Every Memory is sorted by month, with its date, its place and its stickers.",
    openSnapchat: "Open the Snapchat page",
    faqButtonQ: "I can't find “Request Only Memories”.",
    faqButtonA: "Turn on “Export your Memories” first, the blue button shows up right below it.",
    howTitle: "How it works",
    how1Title: "Request your export",
    how1Text: "It takes two minutes on the Snapchat website. The video shows you where to click.",
    how1Link: "Watch the video",
    how2Title: "Drop the ZIP files here",
    how2Text: "They're read in your browser, nothing gets uploaded anywhere.",
    how2Link: "Go to the tool",
    how3Title: "Get your photos back, sorted",
    how3Text: "One folder per month, with the real date, the place and the stickers.",
    how3Link: "See what changes",
    toolProgress: "Import progress",
    toolStep1: "Drop",
    toolStep2: "Check",
    toolStep3: "Save",
    prepTitle: "Before you start",
    prep1: "Your Snapchat ZIP file or files.",
    prep1Link: "How to get them",
    prep2: "Some free disk space, roughly the size of the ZIP files.",
    prep3: "Leave this tab open until the end.",
    browserFolder: "Good news, your browser can save straight into a folder.",
    browserZip:
      "Your browser will give you ZIP files. With Chrome or Edge on a computer, it goes straight into a folder.",
    faqLead: "The quick answers. Got another one? Ask it on GitHub.",
    faqAsk: "Ask a question on GitHub",
    trustLead: "Everything happens on your side, from the first click to the last file.",
  },
  fr: {
    metaTitle: "Télécharger tous ses Souvenirs Snapchat avec la date | SnapMemories",
    metaDescription:
      "Récupère tous tes Souvenirs Snapchat (Memories) sur ton ordi, avec la vraie date, le lieu et les stickers. Gratuit, rien à installer, rien n'est envoyé sur un serveur.",
    ogAlt: "SnapMemories : tes Souvenirs Snapchat rangés par date sur ton ordi",
    videoDescription:
      "Comment exporter tes Souvenirs Snapchat et les récupérer avec leur date, leur lieu et leurs stickers, sur la vraie page de Snapchat.",
    skipLink: "Aller à l'outil",
    navTutorial: "Tuto",
    navFaq: "FAQ",
    otherLanguage: "English",
    eyebrow: "Gratuit · Rien à installer · Rien n'est envoyé",
    heroTitle: "Récupère tous tes Souvenirs Snapchat, avec leur vraie date.",
    heroLead:
      "Sans abonnement, Snapchat te laisse plus accès qu'à ta dernière année de Souvenirs et à tes 5 premiers Go. Pour garder le reste, faut tout exporter. Le souci, c'est que l'export arrive en vrac : pas de date dans les photos, pas de lieu, les stickers à part. SnapMemories remet tout ça en ordre, direct dans ton navigateur.",
    heroCta: "Récupérer mes Souvenirs",
    heroTutorial: "Voir le tuto vidéo",
    heroPoint1: "Photos en qualité d'origine",
    heroPoint2: "Marche même si Snapchat t'envoie plusieurs ZIP",
    heroPoint3: "Open source",
    problemTitle: "Ce qui cloche dans l'export de Snapchat",
    problemLead:
      "Snapchat te rend bien tes fichiers, mais dans un état que ta galerie comprend pas. Voilà à quoi ressemble un vrai export, et ce que SnapMemories arrange.",
    columnTopic: "Quoi",
    columnRaw: "L'export brut de Snapchat",
    columnFixed: "Avec SnapMemories",
    rowDate: "Date",
    rowDateRaw:
      "La date est pas dans la photo. Elle tient juste au nom et à la date du fichier, et ça saute dès que tu le copies ou que tu l'envoies.",
    rowDateFixed:
      "La date et l'heure exactes sont écrites dans chaque photo et chaque vidéo, à ton heure à toi.",
    rowPlace: "Lieu",
    rowPlaceRaw: "Les positions GPS sont rangées à part, dans un fichier technique que personne ouvre.",
    rowPlaceFixed:
      "Le lieu est écrit dans le fichier, donc Google Photos et Apple Photos te le mettent sur la carte.",
    rowStickers: "Stickers",
    rowStickersRaw: "Les textes, stickers et dessins arrivent dans un fichier transparent à côté.",
    rowStickersFixed: "Ils sont recollés sur la photo, comme quand tu l'avais postée.",
    rowSorting: "Rangement",
    rowSortingRaw: "Des centaines de fichiers aux noms illisibles, tous dans le même dossier.",
    rowSortingFixed: "Un dossier par mois, et chaque fichier porte sa date.",
    tutorialTitle: "Le tuto vidéo, sur la vraie page de Snapchat",
    tutorialLead: "51 secondes, avec le son. Clique sur une étape pour sauter direct dessus.",
    toolTitle: "Récupère tes Souvenirs",
    toolLead:
      "T'as déjà tes ZIP ? Dépose-les juste en dessous. Pas encore ? Le tuto au-dessus te montre comment les avoir.",
    dropTitle: "Dépose tes ZIP Snapchat ici",
    dropHint: "ou clique pour les choisir. S'il y en a plusieurs, mets-les tous d'un coup.",
    dropPrivacy: "Rien n'est envoyé : tes fichiers sont lus dans cet onglet, c'est tout.",
    reading: "Lecture de ton export",
    photos: "Photos",
    videos: "Vidéos",
    size: "Taille",
    noteLocated: "Avec un lieu : {count}",
    noteMissing:
      "Pas trouvés dans ces fichiers : {count}. Si Snapchat t'a envoyé plusieurs ZIP, dépose-les tous ensemble.",
    noteLinkOnly:
      "Dispo seulement en lien : {count}. Refais un export sur Snapchat pour les avoir en fichiers.",
    chooseFolder: "Choisir où enregistrer",
    chooseFolderHint:
      "Choisis ou crée un dossier, genre « Souvenirs Snapchat » dans tes Images. Ce qui est déjà dedans est sauté, donc pas de doublons.",
    downloadZip: "Enregistrer en fichiers ZIP",
    downloadZipHint:
      "Ce navigateur sait pas écrire dans un dossier, donc tu vas recevoir des ZIP de 1 Go max. Avec Chrome ou Edge sur ordi, ça va direct dans un dossier.",
    startOver: "Recommencer",
    savingTitle: "Enregistrement en cours",
    savingText: "Laisse cet onglet ouvert jusqu'à la fin.",
    saved: "Enregistrés",
    failed: "Échecs",
    remaining: "Restant",
    stop: "Arrêter",
    stopping: "Arrêt en cours",
    doneTitle: "C'est bon, tout est là !",
    doneText: "Tout est rangé par année et par mois.",
    doneIncompleteTitle: "Presque tout est passé",
    stoppedTitle: "Import arrêté",
    stoppedText: "Redépose les mêmes fichiers plus tard : ce qui est déjà enregistré sera sauté.",
    alreadyThere: "Déjà là",
    partsTitle: "Tes fichiers ZIP",
    partsText: "Les téléchargements se lancent tout seuls. Sinon, clique sur chaque fichier.",
    errorsTitle: "Pas enregistrés",
    importAnother: "Importer un autre export",
    progressLabel: "{done} / {total} souvenirs",
    skippedLabel: "Déjà enregistrés, sautés : {count}.",
    leaveWarning: "Tes Souvenirs sont encore en train d'être enregistrés.",
    errorInvalidZip: "{name}, c'est pas un ZIP de Snapchat.",
    errorNoMemories: "Aucun souvenir trouvé. Vérifie que « Exporter mes souvenirs » était bien activé.",
    errorInvalidHistory: "La liste des souvenirs de cet export est abîmée.",
    errorNothingToImport: "Y'a aucune photo ni vidéo dans ces fichiers.",
    errorFolder: "Ce dossier marche pas. Choisis-en un autre.",
    errorUnexpected: "Un truc a planté. Recharge la page et réessaie.",
    trustTitle: "Tes photos quittent jamais ton appareil",
    trustServerTitle: "Pas de serveur",
    trustServerText:
      "La page lit tes ZIP dans ton navigateur et écrit le résultat sur ton disque. Rien part nulle part.",
    trustQualityTitle: "Qualité d'origine",
    trustQualityText:
      "Une photo sans sticker reste intacte, y'a juste la date et le lieu qui sont ajoutés dedans. Celles avec stickers sont réenregistrées en haute qualité pour les coller.",
    trustOpenTitle: "Open source",
    trustOpenText: "Tout le code est public sur GitHub, n'importe qui peut aller voir ce qu'il fait.",
    faqTitle: "Les questions qu'on me pose",
    faqCostQ: "Combien ça coûte ?",
    faqCostA: "Rien. Pas de compte, pas de pub, pas d'abonnement.",
    faqSafeQ: "C'est safe ?",
    faqSafeA:
      "Ton export quitte jamais ton appareil. Y'a aucun serveur derrière cette page : elle lit les ZIP dans ton navigateur et écrit le résultat sur ton disque.",
    faqTimeQ: "Ça prend combien de temps ?",
    faqTimeA:
      "Côté Snapchat, l'export met entre quelques minutes et quelques heures à être prêt. Après, ça dépend surtout de la taille de l'export et de la vitesse de ton disque.",
    faqPartsQ: "Snapchat m'a envoyé plusieurs ZIP, je fais quoi ?",
    faqPartsA: "C'est normal quand t'as beaucoup de Souvenirs. Dépose-les tous en même temps.",
    faqPhoneQ: "Je peux le faire sur mon tel ?",
    faqPhoneA:
      "Pour un petit export, oui. Pour une grosse photothèque, passe sur un ordi avec Chrome ou Edge.",
    faqGalleryQ: "Comment je les mets dans Google Photos ou iCloud ?",
    faqGalleryA: "Importe juste le dossier que t'as obtenu. La date et le lieu sont lus tout seuls.",
    faqResumeQ: "Et si ça s'arrête en plein milieu ?",
    faqResumeA: "Relance avec le même dossier : ce qui est déjà enregistré est sauté.",
    footerSource: "Open source sur GitHub",
    footerMadeBy: "Fait par qyrn",
    footerDisclaimer: "SnapMemories n'est pas affilié à Snap Inc.",
    step1: "Ouvre « Mes données »",
    step1Caption: "Connecte-toi sur accounts.snapchat.com, puis ouvre « Mes données ».",
    step2: "Active « Exporter mes souvenirs »",
    step2Caption: "Dans « Sélectionner les données à inclure », c'est le premier interrupteur.",
    step3: "Clique sur « Demander uniquement des souvenirs »",
    step3Caption: "Côté Snapchat, c'est fini. Attention, t'as droit qu'à une demande toutes les 72 heures.",
    step4: "Attends le mail",
    step4Caption:
      "Snapchat t'envoie un mail quand c'est prêt, au bout de quelques minutes ou quelques heures. L'export apparaît aussi dans « Vos exports », sur la même page.",
    step5: "« Voir les exports », puis « Télécharger »",
    step5Caption: "Télécharge chaque ZIP sans l'ouvrir. Traîne pas, les exports expirent au bout de 3 jours.",
    step6: "Dépose les ZIP ici",
    step6Caption: "Dépose tous les ZIP d'un coup dans le cadre. Rien n'est envoyé.",
    step7: "Choisis où enregistrer",
    step7Caption: "Choisis un dossier, genre dans tes Images. Ça démarre direct.",
    step8: "C'est rangé",
    step8Caption: "Chaque souvenir est rangé par mois, avec sa date, son lieu et ses stickers.",
    openSnapchat: "Ouvrir la page Snapchat",
    faqButtonQ: "Je trouve pas « Demander uniquement des souvenirs ».",
    faqButtonA: "Active d'abord « Exporter mes souvenirs », le bouton bleu apparaît juste en dessous.",
    howTitle: "Comment ça marche",
    how1Title: "Demande ton export",
    how1Text: "Ça se fait en deux minutes sur le site de Snapchat. La vidéo te montre où cliquer.",
    how1Link: "Voir la vidéo",
    how2Title: "Dépose les ZIP ici",
    how2Text: "Ils sont lus dans ton navigateur, rien n'est envoyé nulle part.",
    how2Link: "Aller à l'outil",
    how3Title: "Récupère tes photos rangées",
    how3Text: "Un dossier par mois, avec la vraie date, le lieu et les stickers.",
    how3Link: "Voir ce qui change",
    toolProgress: "Avancement de l'import",
    toolStep1: "Dépose",
    toolStep2: "Vérifie",
    toolStep3: "Enregistre",
    prepTitle: "Avant de te lancer",
    prep1: "Ton ou tes ZIP Snapchat.",
    prep1Link: "Comment les avoir",
    prep2: "De la place sur ton disque, à peu près la taille des ZIP.",
    prep3: "Laisse cet onglet ouvert jusqu'à la fin.",
    browserFolder: "Bonne nouvelle, ton navigateur peut enregistrer direct dans un dossier.",
    browserZip:
      "Ton navigateur va te sortir des fichiers ZIP. Avec Chrome ou Edge sur ordi, ça va direct dans un dossier.",
    faqLead: "Les réponses rapides. T'en as une autre ? Pose-la sur GitHub.",
    faqAsk: "Poser une question sur GitHub",
    trustLead: "Tout se passe chez toi, du premier clic au dernier fichier.",
  },
} as const satisfies Record<Language, Record<string, string>>;

export type MessageKey = keyof (typeof STRINGS)["en"];

export const PAGE_PATHS: Record<Language, string> = { en: "/", fr: "/fr/" };

export const FAQ_KEYS: Array<[MessageKey, MessageKey]> = [
  ["faqCostQ", "faqCostA"],
  ["faqSafeQ", "faqSafeA"],
  ["faqTimeQ", "faqTimeA"],
  ["faqPartsQ", "faqPartsA"],
  ["faqButtonQ", "faqButtonA"],
  ["faqPhoneQ", "faqPhoneA"],
  ["faqGalleryQ", "faqGalleryA"],
  ["faqResumeQ", "faqResumeA"],
];
