export type Language = "fr" | "en";

export const STRINGS = {
  en: {
    metaTitle: "Save your Snapchat Memories with dates and places | SnapMemories",
    metaDescription:
      "Move your Snapchat Memories to your computer with their real date, place and stickers. Free, nothing to install, nothing uploaded.",
    ogAlt: "SnapMemories: your Snapchat Memories, sorted by date on your computer",
    skipLink: "Skip to the tool",
    navTutorial: "Tutorial",
    navFaq: "FAQ",
    otherLanguage: "Français",
    eyebrow: "Free · Nothing to install · Nothing uploaded",
    heroTitle: "Bring your Snapchat Memories home.",
    heroLead:
      "Without a subscription, Snapchat now only keeps your Memories from the last year and your oldest 5 GB within reach. SnapMemories turns your export into a real photo library: every photo and video gets its date, place and stickers back.",
    heroCta: "Get my Memories back",
    heroTutorial: "Watch the video tutorial",
    heroPoint1: "Original photo quality",
    heroPoint2: "Works with exports split into several ZIP files",
    heroPoint3: "Open source",
    problemTitle: "Why the raw export isn't enough",
    problemLead:
      "Snapchat does give your files back, just not in a shape a photo app understands. Here is what a real export looks like, and what SnapMemories fixes.",
    columnTopic: "What",
    columnRaw: "Raw Snapchat export",
    columnFixed: "With SnapMemories",
    rowDate: "Date",
    rowDateRaw:
      "The date is not stored inside the photos. It only lives in the file name and file date, which change as soon as you copy or send them.",
    rowDateFixed: "The exact date and time are written inside every photo and video, in your time zone.",
    rowPlace: "Place",
    rowPlaceRaw: "GPS positions sit apart, in a technical file nobody opens.",
    rowPlaceFixed: "The place is written in the file, so Google Photos and Apple Photos show it on a map.",
    rowStickers: "Stickers",
    rowStickersRaw: "Text, stickers and drawings come as a separate transparent file.",
    rowStickersFixed: "They are put back on the photo, the way you posted it.",
    rowSorting: "Sorting",
    rowSortingRaw: "Hundreds of files with unreadable names in a single folder.",
    rowSortingFixed: "One folder per month, one file name per date.",
    tutorialTitle: "The video tutorial, on the real Snapchat page",
    tutorialLead: "51 seconds, with sound. Click a step to jump straight to it.",
    toolTitle: "Get your Memories back",
    toolLead:
      "Already have your ZIP files? Drop them below. Not yet? The tutorial above shows how to get them.",
    dropTitle: "Drop your Snapchat ZIP files",
    dropHint: "or click to choose them. Drop every part at once.",
    dropPrivacy: "Nothing is uploaded: your files are read inside this tab.",
    reading: "Reading your export",
    photos: "Photos",
    videos: "Videos",
    size: "Size",
    noteLocated: "With a location: {count}",
    noteMissing:
      "Not found in these files: {count}. If Snapchat sent several ZIP files, drop them all together.",
    noteLinkOnly: "Only available as download links: {count}. Use the Windows app for those.",
    chooseFolder: "Choose where to save",
    chooseFolderHint:
      "Pick or create a folder, for example “Snapchat Memories” in your Pictures. Memories already saved there are skipped.",
    downloadZip: "Save as ZIP files",
    downloadZipHint:
      "This browser can't write into a folder, so you'll get ZIP files of 1 GB max. Chrome or Edge on a computer save straight into a folder.",
    startOver: "Start over",
    savingTitle: "Saving your memories",
    savingText: "Keep this tab open until the end.",
    saved: "Saved",
    failed: "Failed",
    remaining: "Remaining",
    stop: "Stop",
    stopping: "Stopping",
    doneTitle: "Memories saved!",
    doneText: "Everything is sorted by year and month.",
    doneIncompleteTitle: "Almost everything saved",
    stoppedTitle: "Import stopped",
    stoppedText: "Drop the same files again later: memories already saved are skipped.",
    alreadyThere: "Already there",
    partsTitle: "Your ZIP files",
    partsText: "Downloads should start by themselves. If not, click each file.",
    errorsTitle: "Not saved",
    importAnother: "Import another export",
    progressLabel: "{done} / {total} memories",
    skippedLabel: "Already saved, skipped: {count}.",
    leaveWarning: "Your memories are still being saved.",
    errorInvalidZip: "{name} is not a ZIP file from Snapchat.",
    errorNoMemories: "No memories found. Check that “Export your Memories” was turned on.",
    errorInvalidHistory: "The memories list in this export is damaged.",
    errorNothingToImport: "No photos or videos found in these files.",
    errorFolder: "This folder can't be used. Choose another one.",
    errorUnexpected: "Something went wrong. Reload the page and try again.",
    trustTitle: "Your photos never leave your device",
    trustServerTitle: "No server",
    trustServerText:
      "This page reads your ZIP files inside your browser and writes the result to your disk. Nothing is sent anywhere.",
    trustQualityTitle: "Original quality",
    trustQualityText: "Photos are not recompressed. Only the date and place information is added.",
    trustOpenTitle: "Open source",
    trustOpenText: "All the code is public on GitHub, so anyone can check what it does.",
    faqTitle: "Questions",
    faqCostQ: "How much does it cost?",
    faqCostA: "Nothing. No account, no ads, no subscription.",
    faqSafeQ: "Is it safe?",
    faqSafeA:
      "Your export never leaves your device. There is no server behind this page: it reads the ZIP files in your browser and writes the result to your disk.",
    faqTimeQ: "How long does it take?",
    faqTimeA:
      "Snapchat needs a few minutes to a few hours to prepare the export. After that, the time depends mostly on the size of your export and the speed of your disk.",
    faqPartsQ: "Snapchat sent me several ZIP files.",
    faqPartsA: "That's normal for big exports. Drop all of them at the same time.",
    faqPhoneQ: "Can I do it on my phone?",
    faqPhoneA: "It works for small exports. For a big library, use a computer with Chrome or Edge.",
    faqGalleryQ: "How do I put them in Google Photos or iCloud?",
    faqGalleryA: "Upload the folder you got. The date and place are read automatically.",
    faqResumeQ: "What if it stops halfway?",
    faqResumeA: "Start again with the same folder: memories already saved are skipped.",
    faqAppQ: "Is there an app?",
    faqAppA: "Yes, for Windows. It's useful for very old exports that only contain download links.",
    faqAppLink: "Download the Windows app",
    footerSource: "Open source on GitHub",
    footerMadeBy: "Made by qyrn",
    footerDisclaimer: "SnapMemories is not affiliated with Snap Inc.",
    step1: "Open “My Data”",
    step1Caption: "Sign in on accounts.snapchat.com, then open “My Data”.",
    step2: "Turn on “Export your Memories”",
    step2Caption: "In “Select data to include”, it's the first switch.",
    step3: "Click “Request Only Memories”",
    step3Caption: "That's all on the Snapchat side. You can only make one request every 72 hours.",
    step4: "Wait for the email",
    step4Caption:
      "Snapchat emails you when the export is ready, after a few minutes or a few hours. It then shows up in “Your exports” on the same page.",
    step5: "“See exports”, then “Download”",
    step5Caption: "Download every ZIP file without opening it. Exports expire after 3 days.",
    step6: "Drop the ZIP files here",
    step6Caption: "Drop every ZIP file at once into the drop box. Nothing is uploaded.",
    step7: "Choose where to save",
    step7Caption: "Pick a folder, for example in your Pictures. Saving starts right away.",
    step8: "All sorted",
    step8Caption: "Every memory is sorted by month, with its date, its place and its stickers.",
    openSnapchat: "Open the Snapchat page",
    faqButtonQ: "I can't find “Request Only Memories”.",
    faqButtonA: "Turn on “Export your Memories” first: the blue button appears right below it.",
  },
  fr: {
    metaTitle: "Récupérer ses Souvenirs Snapchat (Memories) avec date et lieu | SnapMemories",
    metaDescription:
      "Rapatrie tes Souvenirs Snapchat sur ton ordinateur avec la vraie date, le lieu et les stickers. Gratuit, rien à installer, rien n'est envoyé.",
    ogAlt: "SnapMemories : tes Souvenirs Snapchat rangés par date sur ton ordinateur",
    skipLink: "Aller à l'outil",
    navTutorial: "Tuto",
    navFaq: "FAQ",
    otherLanguage: "English",
    eyebrow: "Gratuit · Rien à installer · Rien n'est envoyé",
    heroTitle: "Tes Souvenirs Snapchat, rapatriés chez toi.",
    heroLead:
      "Sans abonnement, Snapchat ne te laisse plus que les Souvenirs de la dernière année et tes 5 premiers Go. SnapMemories transforme ton export en vraie photothèque : chaque photo et vidéo retrouve sa date, son lieu et ses stickers.",
    heroCta: "Récupérer mes Souvenirs",
    heroTutorial: "Voir le tuto vidéo",
    heroPoint1: "Photos en qualité d'origine",
    heroPoint2: "Marche avec les exports en plusieurs ZIP",
    heroPoint3: "Open source",
    problemTitle: "Pourquoi l'export brut ne suffit pas",
    problemLead:
      "Snapchat te rend bien tes fichiers, mais pas dans un état qu'une galerie photo comprend. Voici à quoi ressemble un vrai export, et ce que SnapMemories corrige.",
    columnTopic: "Quoi",
    columnRaw: "Export brut de Snapchat",
    columnFixed: "Avec SnapMemories",
    rowDate: "Date",
    rowDateRaw:
      "La date n'est pas inscrite dans les photos. Elle tient au nom et à la date du fichier, qui changent dès que tu les copies ou les envoies.",
    rowDateFixed:
      "La date et l'heure exactes sont écrites dans chaque photo et chaque vidéo, à ton fuseau horaire.",
    rowPlace: "Lieu",
    rowPlaceRaw: "Les positions GPS sont rangées à part, dans un fichier technique que personne n'ouvre.",
    rowPlaceFixed:
      "Le lieu est écrit dans le fichier : Google Photos et Apple Photos l'affichent sur la carte.",
    rowStickers: "Stickers",
    rowStickersRaw: "Textes, stickers et dessins arrivent dans un fichier séparé et transparent.",
    rowStickersFixed: "Ils sont recollés sur la photo, comme tu l'avais publiée.",
    rowSorting: "Rangement",
    rowSortingRaw: "Des centaines de fichiers aux noms illisibles dans un seul dossier.",
    rowSortingFixed: "Un dossier par mois, un nom de fichier par date.",
    tutorialTitle: "Le tuto vidéo, sur la vraie page Snapchat",
    tutorialLead: "51 secondes, avec le son. Clique sur une étape pour y aller directement.",
    toolTitle: "Récupère tes Souvenirs",
    toolLead:
      "Tu as déjà tes ZIP ? Dépose-les ci-dessous. Pas encore ? Le tuto juste au-dessus montre comment les obtenir.",
    dropTitle: "Dépose tes ZIP Snapchat",
    dropHint: "ou clique pour les choisir. Dépose toutes les parties d'un coup.",
    dropPrivacy: "Rien n'est envoyé : tes fichiers sont lus dans cet onglet.",
    reading: "Lecture de ton export",
    photos: "Photos",
    videos: "Vidéos",
    size: "Taille",
    noteLocated: "Avec un lieu : {count}",
    noteMissing:
      "Introuvables dans ces fichiers : {count}. Si Snapchat t'a envoyé plusieurs ZIP, dépose-les tous ensemble.",
    noteLinkOnly: "Disponibles seulement sous forme de lien : {count}. Utilise l'app Windows pour celles-là.",
    chooseFolder: "Choisir où enregistrer",
    chooseFolderHint:
      "Choisis ou crée un dossier, par exemple « Souvenirs Snapchat » dans tes Images. Les souvenirs déjà enregistrés dedans sont ignorés.",
    downloadZip: "Enregistrer en fichiers ZIP",
    downloadZipHint:
      "Ce navigateur ne peut pas écrire dans un dossier : tu recevras des ZIP de 1 Go maximum. Chrome ou Edge sur ordinateur enregistrent directement dans un dossier.",
    startOver: "Recommencer",
    savingTitle: "Enregistrement en cours",
    savingText: "Garde cet onglet ouvert jusqu'à la fin.",
    saved: "Enregistrés",
    failed: "Échecs",
    remaining: "Restant",
    stop: "Arrêter",
    stopping: "Arrêt en cours",
    doneTitle: "Souvenirs enregistrés !",
    doneText: "Tout est rangé par année et par mois.",
    doneIncompleteTitle: "Presque tout est enregistré",
    stoppedTitle: "Import arrêté",
    stoppedText: "Redépose les mêmes fichiers plus tard : les souvenirs déjà enregistrés seront ignorés.",
    alreadyThere: "Déjà là",
    partsTitle: "Tes fichiers ZIP",
    partsText: "Les téléchargements démarrent tout seuls. Sinon, clique sur chaque fichier.",
    errorsTitle: "Non enregistrés",
    importAnother: "Importer un autre export",
    progressLabel: "{done} / {total} souvenirs",
    skippedLabel: "Déjà enregistrés, ignorés : {count}.",
    leaveWarning: "Tes souvenirs sont encore en cours d'enregistrement.",
    errorInvalidZip: "{name} n'est pas un ZIP de Snapchat.",
    errorNoMemories: "Aucun souvenir trouvé. Vérifie que « Exporter mes souvenirs » était activé.",
    errorInvalidHistory: "La liste des souvenirs de cet export est abîmée.",
    errorNothingToImport: "Aucune photo ni vidéo dans ces fichiers.",
    errorFolder: "Ce dossier ne peut pas être utilisé. Choisis-en un autre.",
    errorUnexpected: "Un problème est survenu. Recharge la page et réessaie.",
    trustTitle: "Tes photos ne quittent jamais ton appareil",
    trustServerTitle: "Pas de serveur",
    trustServerText:
      "La page lit tes ZIP directement dans ton navigateur et écrit le résultat sur ton disque. Rien n'est envoyé nulle part.",
    trustQualityTitle: "Qualité d'origine",
    trustQualityText:
      "Les photos ne sont pas recompressées. Seules les infos de date et de lieu sont ajoutées.",
    trustOpenTitle: "Open source",
    trustOpenText: "Tout le code est public sur GitHub : n'importe qui peut vérifier ce qu'il fait.",
    faqTitle: "Questions",
    faqCostQ: "Combien ça coûte ?",
    faqCostA: "Rien. Pas de compte, pas de pub, pas d'abonnement.",
    faqSafeQ: "C'est sûr ?",
    faqSafeA:
      "Ton export ne quitte jamais ton appareil. Il n'y a aucun serveur derrière cette page : elle lit les ZIP dans ton navigateur et écrit le résultat sur ton disque.",
    faqTimeQ: "Ça prend combien de temps ?",
    faqTimeA:
      "Snapchat met de quelques minutes à quelques heures à préparer l'export. Ensuite, la durée dépend surtout de la taille de ton export et de la vitesse de ton disque.",
    faqPartsQ: "Snapchat m'a envoyé plusieurs ZIP.",
    faqPartsA: "C'est normal pour les gros exports. Dépose-les tous en même temps.",
    faqPhoneQ: "Je peux le faire sur mon téléphone ?",
    faqPhoneA:
      "Oui pour les petits exports. Pour une grosse photothèque, utilise un ordinateur avec Chrome ou Edge.",
    faqGalleryQ: "Comment les mettre dans Google Photos ou iCloud ?",
    faqGalleryA: "Importe le dossier obtenu. La date et le lieu sont lus automatiquement.",
    faqResumeQ: "Et si ça s'arrête en plein milieu ?",
    faqResumeA: "Relance avec le même dossier : les souvenirs déjà enregistrés sont ignorés.",
    faqAppQ: "Il existe une app ?",
    faqAppA:
      "Oui, pour Windows. Elle sert pour les très vieux exports qui ne contiennent que des liens de téléchargement.",
    faqAppLink: "Télécharger l'app Windows",
    footerSource: "Open source sur GitHub",
    footerMadeBy: "Fait par qyrn",
    footerDisclaimer: "SnapMemories n'est pas affilié à Snap Inc.",
    step1: "Ouvre « Mes données »",
    step1Caption: "Connecte-toi sur accounts.snapchat.com, puis ouvre « Mes données ».",
    step2: "Active « Exporter mes souvenirs »",
    step2Caption: "Dans « Sélectionner les données à inclure », c'est le premier interrupteur.",
    step3: "Clique sur « Demander uniquement des souvenirs »",
    step3Caption: "C'est tout côté Snapchat. Tu ne peux faire qu'une demande toutes les 72 heures.",
    step4: "Attends le mail",
    step4Caption:
      "Snapchat t'écrit quand l'export est prêt, après quelques minutes ou quelques heures. Il apparaît alors dans « Vos exports », sur la même page.",
    step5: "« Voir les exports », puis « Télécharger »",
    step5Caption: "Télécharge chaque ZIP sans l'ouvrir. Les exports expirent au bout de 3 jours.",
    step6: "Dépose les ZIP ici",
    step6Caption: "Dépose tous les ZIP d'un coup dans le cadre de dépôt. Rien n'est envoyé.",
    step7: "Choisis où enregistrer",
    step7Caption: "Choisis un dossier, par exemple dans tes Images. L'enregistrement démarre aussitôt.",
    step8: "C'est rangé",
    step8Caption: "Chaque souvenir est rangé par mois, avec sa date, son lieu et ses stickers.",
    openSnapchat: "Ouvrir la page Snapchat",
    faqButtonQ: "Je ne trouve pas « Demander uniquement des souvenirs ».",
    faqButtonA: "Active d'abord « Exporter mes souvenirs » : le bouton bleu apparaît juste en dessous.",
  },
} as const satisfies Record<Language, Record<string, string>>;

export type MessageKey = keyof (typeof STRINGS)["en"];

export const PAGE_PATHS: Record<Language, string> = { en: "/", fr: "/fr/" };

export const FAQ_KEYS: Array<[MessageKey, MessageKey]> = [
  ["faqCostQ", "faqCostA"],
  ["faqSafeQ", "faqSafeA"],
  ["faqTimeQ", "faqTimeA"],
  ["faqPartsQ", "faqPartsA"],
  ["faqButtonQ", "faqButtonA"],
  ["faqPhoneQ", "faqPhoneA"],
  ["faqGalleryQ", "faqGalleryA"],
  ["faqResumeQ", "faqResumeA"],
  ["faqAppQ", "faqAppA"],
];
